
///rest client

@URL=http://localhost:3006/receita
@TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsIm5vbWUiOiJqdWMgYW1vcmEiLCJlbWFpbCI6InpAZ21haWwuY29tIiwiaWF0IjoxNjk5NTUxMjg0LCJleHAiOjE2OTk1NTQ4ODR9._P25tZ5w5qFcwoVDEjPwnqhbBOXepnzKk7l0JsSpJQY

###Obter todoa as pessoas

GET {{URL}}


###

GET {{URL}}/2

GET {{URL}}/4

###criar receita
POST {{URL}}
Authorization: {{TOKEN}}
Content-Type: application/json

{
  "titulo" : "ddd",
  "descricao" : "ddddddddddddddd",
  "ingredientes" : "Ad;ddd;ddd;d",
  "instrucoes" : "aa;aaa;aa;aa;",
  "id_usuario" : 2,
  "criacao" : "2020-10-12"
}


###atualizar receita
PUT {{URL}}/2
Content-Type: application/json

{
  "titulo" : "aFFF",
  "descricao" : "dG",
  "ingredientes" : "Ad;ddd;ddd;d",
  "instrucoes" : "aaa;aa;",
  "id_usuario" : 2
}


### deletar receita
DELETE {{URL}}/2
Authorization:{{TOKEN}}