
///rest client

@URL=http://localhost:3006/receita
@TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwibm9tZSI6IkRhbmllbCBNYWhsIEdyZWdvcmluaSIsImVtYWlsIjoiYXplQGdtYWlsLmNvbSIsImlhdCI6MTcwMDYwNDgzMywiZXhwIjoxNzAwNjA4NDMzfQ.mjzn1id_6o4ZxscVMhaU9zEChnoFfRM_EYHkinVkrlg

###Obter todoa as receitas

GET {{URL}}
###

GET {{URL}}/2

GET {{URL}}/4

###criar receita
POST {{URL}}
Authorization: {{TOKEN}}
Content-Type: application/json

{
  "titulo": "Massa Carbonara",
  "descricao": "Prato de massa italiano com bacon, ovos e queijo parmesão",
  "ingredientes": "Espaguete; Bacon; Ovos; Queijo parmesão",
  "instrucoes": "Cozinhe o espaguete; Misture bacon, ovos e queijo; Misture com o espaguete cozido.",
  "id_usuario": 47,
  "criacao": "2022-10-01"
}











###atualizar receita
PUT {{URL}}/2
Content-Type: application/json

{
  "titulo" : "aFFF",
  "descricao" : "dG",
  "ingredientes" : "Ad;ddd;ddd;d",
  "instrucoes" : "aaa;aa;",
  "id_usuario" : 2
}


### deletar receita
DELETE {{URL}}/2
Authorization:{{TOKEN}}