
///rest client

@URL=http://localhost:3006/usuario

@TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsIm5vbWUiOiJqdWMgYW1vcmEiLCJlbWFpbCI6InpAZ21haWwuY29tIiwiaWF0IjoxNjk5NDQ1NzE3LCJleHAiOjE2OTk0NDkzMTd9.SjF85DxnlOnCJH8HOV3yQQ426lOyyuFt8mGnaurEq8o
###Obter todoa as pessoas

GET {{URL}}
Authorization:{{TOKEN}}
###

GET {{URL}}/1
Authorization:{{TOKEN}}
###
GET {{URL}}/7
Authorization:{{TOKEN}}

###g
POST {{URL}}
Content-Type: application/json

{
  "nome" : "daniel",
  "email" : "zddsse@gmail.com",
  "senha" : "123456",
  "nascimento" : "2020-09-19",
  "telefone" : "23232323"
}



###atualizar usuario
PUT {{URL}}/2
Content-Type: application/json

{
  "nome" : "ddd",
  "email" : "Aze@gmail.com",
  "senha" : "A",
  "nascimento" : "2020-09-2",
  "telefone" : "1"
}


### deletar pessoa

DELETE {{URL}}/1