
///rest client

@URL=http://localhost:3006/usuario

@TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwibm9tZSI6IkRhbmllbCBNYWhsIEdyZWdvcmluaSIsImVtYWlsIjoiYXplQGdtYWlsLmNvbSIsImlhdCI6MTcwMDY1MTUyNSwiZXhwIjoxNzAwNjU1MTI1fQ.Se1LV4-LBQ_HNe4l8WOrhafg-gViuJj2CkeEtWFAFag
###Obter todoa as pessoas

GET {{URL}}
Authorization:{{TOKEN}}
###

GET {{URL}}/2
Authorization:{{TOKEN}}

###
GET {{URL}}/7
Authorization:{{TOKEN}}

###g
POST {{URL}}
Content-Type: application/json

{
  "nome" : "daniel",
  "email" : "zddssce@gmail.com",
  "senha" : "123456",
  "nascimento" : "2020-09-19",
  "telefone" : "23232323"
}
 

 
###atualizar usuario
PUT {{URL}}/2
Content-Type: application/json
Authorization:{{TOKEN}}

{
  "nome" : "ddaaggdddfgd",
  "email" : "aze@gmail.com",
  "senha" : "A",
  "nascimento" : "2020-09-2",
  "telefone" : "1"
}


### deletar pessoa
DELETE {{URL}}/48
Authorization:{{TOKEN}}